### ISSUE TITLE
constrain datacite imports to datasets

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backend#159]
only records with resourceTypeGeneral Dataset can be imported, other types should give an error

@sdebodt what other types can we imports as datasets? (Datapaper, Image, ...)

**Comment by nics** [comment]
related issue: #110

**Comment by nicolasfranck** [comment]
* `Add publication` -> `source` is always `crossref`
* `Add dataset` -> `source` is always `datacite`
* Remove switch from `crossref` to `datacite` from [importer.pm](https://github.ugent.be/Universiteitsbibliotheek/librecat/blob/cce6e0f26032ddef02a97d5b952dde62f8e2b878/lib/LibreCat/App/Catalogue/Route/importer.pm#L23) in old LibreCat so that no datasets could be added accidentally (happened? @nics ) using the old interface.
* As the datacite importer is now restricted to datasets only, then [this mapping](https://github.ugent.be/Universiteitsbibliotheek/librecat/blob/master/ugent/fixes/from_datacite.fix#L4) should be updated as well?

**Comment by nics** [comment]
resolved by changes in librecat
