### ISSUE TITLE
add help in project popup

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#241]
**Describe the improvement**
To add a project to a dataset/publication, a popup is opened when clicking "Add project". In this popup, add the sentence "Select one or more projects as known in GISMO and Research Explorer".

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/146382522-8c748441-4b04-4857-ab64-51d341b30ba3.png)

**Comment by nicolasfranck** [comment]
@nics @sdebodt something like this? https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_datalist
If you click in the input you see an automatic dropdown, but you can still fill in your own text.

Important: as it is a sort of autocomplete, there is no way to hide the full url of a license behind a short label,
so that might be a "problem".

**Comment by nics** [comment]
is this text still needed if the search improves?

**Comment by nics** [comment]
ok
