### ISSUE TITLE
pressing enter in keywords box results clears in save of "additional information" and loss of last keyword

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#269]
**Describe the improvement**
When I want to add a keyword and press "enter" instead of click the save button, then the edit mode is left, but the keyword is not saved. Either change such that enter does not result in save or that edit mode is left and keyword is saved.

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/150819707-a70ea43d-83f1-4200-87df-b39ba1474884.png)

**Comment by nicolasfranck** [comment]
At the moment there is no "save on enter" in general.
Regular forms have that though.
I guess because works too fast (oops I didn't mean to do that!).

Also, in regular forms, you return to edit form after submission,
but in this case you get the readonly version after save which is
a bit annoying when you accidentally hit enter (because you're
used to hitting enter).

**Comment by nics** [comment]
fixed by the switch to modals
