### ISSUE TITLE
change tooltip for data format

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#298]
**Describe the improvement**
To further help users to enter a good data format, I would like to change the tooltip for data format to:

"Technical format of the data (select a [Internet Media Type](https://www.iana.org/assignments/media-types/media-types.xhtml) from the autocomplete drop-down menu (e.g. text/csv, image/jpeg) or enter [free text](https://en.wikipedia.org/wiki/List_of_file_formats))"

**Comment by nics** [comment]
(datasets)

**Comment by netsensei** [comment]
I've added the tooltip, but I had to alter the default behavior of tooltips.

Hovering over a tooltip link displays the tooltip, but leaving the tooltip link immediately hides the tooltip again. Since the text in this particular tooltip has a hyperlinks, it's therefor not possible to click on those links.

There are two options. Either delay tooltips being hidden again, or hide tooltips when another element gets focus (e.g. when a user clicks elsewhere). When testing, adding a delay up to 500ms wasn't enough to be able to move the cursor and click a link inside the tooltip. Extending the delay above 500ms meant that tooltips were being displayed for far too long, obstructing the view on e.g. form elements. And so, the second option has been implemented here.

**Comment by nicolasfranck** [comment]
@netsensei or make the tooltip only appear on click (and disappear on second click or on side click)? It gives the user more control, and makes the implementation simpler

**Comment by sdebodt** [comment]
address together with https://github.com/ugent-library/biblio-backend/issues/335

**Comment by netsensei** [comment]
Should be fixed with (next) release to `dev`. The tooltip is displayed when the icon is clicked. The tooltip closes again when a click happens elsewhere in the browser canvas. This leaves ample time for users to click on any links displayed inside the tooltip.
