### ISSUE TITLE
Eliminate panel expand/collapse

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backend#361]
Anniek and the biblio team ask that the publication details panel in Description is expanded by default so they can get some immediate metadata feedback.

@rcallewaert and I both think it's better to just eliminate expand/collapse of (most?) panels because it's easy to miss some information and it's sometimes confusing + we get the design more in line with the admin ui. What do you think @mietcls and @netsensei?

Alternatively we can keep the collapse arrow but expand everything by default.

**Comment by mietcls** [comment]
Agreed that it will probably be superfluous to have the collapse panels in the first place.

However, we should take the researchers feedback into account – as we have a different view for the reviewers. This is probably a good suggestion, so I don't mind for this one. But I would not want to confuse the two.

Can we wait with UI adaptions until we have more feedback (the locking issue is a different story)?

**Comment by netsensei** [comment]
I agree with @mietcls. Researchers and reviewers are distinct roles each arriving at the UI with their own unique concerns. I'd like to see some feedback from both groups first to avoid spending too much time adding small, hard to maintain tweaks to the templates.

**Comment by sdebodt** [comment]
There are some remarks about the collapsing/expanding of metadata sections from the pilot group. I think these are due to the fact that you can click on the arrow or the space next to it to expand, but if you want to collapse again only clicking on the space next to it works. Clicking on the arrow to collapse gives no response.

Earlier we decided to collapse everything because then a user gets an overview of everything that needs to be completed. When everything is expanded by default than it is not obvious that there is also a department, project and additional information section as the publication details section is so long. Guiding users through the tabs and through the different sections could help to overcome this issue. 

Note that in DMPonline.be all sections are collapsed by default (in case you would want to have consistency).

**Comment by mietcls** [comment]
Apart from the entanglement with the saving / autosave / ... discussion – does this need more refinement? Are there any outstanding questions about how? @nics @netsensei 

eg. removing collapse elapse, showing everything all at once, which tabs to merge, ....
