### ISSUE TITLE
As a reviewer, when I use Biblio in a split screen, the functionalities must still be visible, legible, clear and usable so I can see multiple browser windows at the same time.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#364]
# Main Story

As a reviewer, when I use Biblio in a split screen, the functionalities must still be visible, legible, clear and usable so I can compare records with information I see in an other browser window at the same time.

# Success Criteria

- - [ ] When I land on the list or table overview, I can adapt filters and navigate through the different records. 
- - [ ] I can see the full record, edit, save and publish without anything else distracting me.
- - [ ] I can navigate back to the list or table overview.
- - [ ] When I want to switch between users or applications within Biblio, I can – but I do not need to see these possibilities at all times.

##  Out of scope
- Full functionality on mobile.

# Additional info

## Related stories
- **Accessibility**: In the bigger scope of things our researchers and librarians need to be able to zoom in on the application without functionality breaking. Story to be written.

## Context

What the application looks like in split mode right now:

### Current application

Overview
![Image](https://user-images.githubusercontent.com/1572885/168997495-e94341cb-4e2c-46a9-a0df-85ed0456db14.png)
![Image](https://user-images.githubusercontent.com/1572885/168997494-e329c1aa-7a56-4031-9ade-60ca92f342f3.png)

Detail
![Image](https://user-images.githubusercontent.com/1572885/168996667-0a7a8760-eaab-4455-8358-1d220073a314.png)

### Current prototype

Overview
![Image](https://user-images.githubusercontent.com/1572885/168997684-cffc87a7-4a03-43fd-b07e-d42b8f40b717.png)

Detail
![Image](https://user-images.githubusercontent.com/1572885/168996949-51443773-0a11-42a4-9c8d-3f905224c206.png)

Modals
![Image](https://user-images.githubusercontent.com/1572885/169013578-12677b37-9681-44a4-8a19-7f8a8be591b8.png)

![Image](https://user-images.githubusercontent.com/1572885/169013715-c5d26fe8-a092-4649-92a5-859ea8eb8248.png)

### Current new implementation

Overview

![Image](https://user-images.githubusercontent.com/1572885/168997873-f0812c7f-2df4-43f1-b228-1018255cbd56.png)

Detail
![Image](https://user-images.githubusercontent.com/1572885/168996950-d5057d1f-d640-4daa-b163-81de0ff0cc06.png)

**Comment by mietcls** [comment]
Emily will share which files changed and what changed (probably in August).

**Comment by emilyvandewalle** [comment]
These are the main changes in terms of reponsiveness:


## Responsive toolbars

<img width="761" alt="image" src="https://user-images.githubusercontent.com/36261498/179254877-12d6f3e1-7140-4548-a37d-9dd78bc391ff.png">

I added a `bc-toolbar-responsive` class which will make the content wrap on screens smaller than 768px (medium breakpoint). This can be added to toolbars that contain many items that would otherwise overlap on smaller screens.

**_bc-toolbar.scss**

``` scss
.bc-toolbar-responsive {
  @include media-breakpoint-down(md) {
    flex-wrap: wrap;
    .bc-toolbar-left,
    .bc-toolbar-right {
      width: 100%;
    }

    .bc-toolbar-right {
      justify-content: flex-start;
    }
  }

  height: auto;
}
```


## Horizontal scroll on tables

Large tables can be made horizontally scrollable with a `table-responsive` wrapper class around tables. This class comes with [Bootstrap](https://getbootstrap.com/docs/4.6/content/tables/#contextual-classes)

<img width="739" alt="image" src="https://user-images.githubusercontent.com/36261498/179254925-49ff6dee-d10f-4723-9a30-87112d7d2920.png">



## Tabs 

<img width="763" alt="image" src="https://user-images.githubusercontent.com/36261498/179256221-92b0ff0d-344d-452b-80ff-93ff8a42b2c3.png">

For the toolbar with many tabs in the overview I set up a construction with `d-none`,`d-md-flex` and `d-lg-flex` to limit the amount of items shown on smaller screens

For other tab navigations we can make them horizontally scrollable by adding a `nav-tabs-scrollable` class or also limit the amount of items and use the more menu like above on smaller screens.

**/content/scss/bootstrap-additions/_nav.scss**
``` scss
.nav-tabs-scrollable {
  overflow: auto;
  flex-wrap: nowrap;
  .nav-link {
    white-space: nowrap;
  }
}

```


## Changes to the forms

The horizontal forms generally use following grid classes: 

- `col-lg-5 col-xl-3` for the labels 
- `col-lg-7 col-xl-9` for the inputs.  

These column classes come with Bootstrap. These should ensure enough space for the labels in most cases. On smaller screens the forms will be stacked with the labels on top.

``` html 
<div class="form-group form-row">
      <label class="col-lg-5 col-xl-3 col-form-label" for="doi">DOI</label>
      <div class="col-lg-7 col-xl-9">
          <input class="form-control form-control-w-medium" type="text" value="10.1016/j.ajp.2020.102188" id="#doi">
      </div>
  </div>
```


## Grid layout

<img width="759" alt="image" src="https://user-images.githubusercontent.com/36261498/179259372-080e287a-9aaa-4f0a-84b9-63600d38a7b9.png">

For grid layouts like these we can also use the column classes and control the spacing between the items via the responsive spacing classes that come with Bootstrap like `mb-md-0`

``` html
<div class="row">
    <div class="col-md mb-6 mb-md-0">
        <div class="card h-100">
               <!-- card content -->
        </div>
    </div>
    <div class="col-md mb-6 mb-md-0">
        <div class="card h-100">
               <!-- card content -->
        </div>
    </div>
</div>
```


## Min width of 750px
I tried to make it as responsive as possible, but got stuck making it functional on small screens. 

Therefore I'd suggest adding a minimum width of 750px and make the content horizontally scrollable for now for screens that are smaller than 750px. It's not ideal, but we can take a look later to design the mobile navigation. What do you think?

This would be the layout frame:
``` html
<div class="u-horizontal-scroll h-100 w-100">
    <div class="u-min-w-750 h-100">
        <header>
               <!--- Header goes here -->
       </header>
        <main>
            <div class="d-flex h-100">
               <!--- Main content goes here -->
            </div>
        </main>
    </div>
</div>
```

**/content/scss/utilities/_u-generic.scss**
``` scss
.u-horizontal-scroll {
  overflow-x: auto;
  overflow-y: auto;
}

.u-min-w-750 {
  min-width: 75rem;
}
```

We can add this meta tag so the content is displayed at a 750px width by default from where the user could zoom in to view and fill out the content:

``` html
<meta name="viewport" content="width=750" />
```

**Comment by mietcls** [comment]
Closing this one, will start splitting up implementations in different issues like https://github.com/ugent-library/biblio-backend/issues/470
