### ISSUE TITLE
As a librarian or researcher I can see more details about a topic in a card without having to go to the detail page

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#399]
# Story
- As a librarian or researcher, when I for example, see a list of for example publications, projects or datasets, I can see the most important information first. When I want a bit more information without going into the detailed view, I can do so without leaving the screen.

# Success Criteria
- [ ] I can see the most important information without clicking, only scrolling
- [ ] I can see more information without going to the detailed view
- [ ] This is an pattern we can reuse for different types of cards and information.

# Context

Right now we are forcing a lot of information in a small card. This information is sometimes is not needed on first glance, but should not force someone to go to a detail page if they are in an explorative modus.

Example: record
<img width="1018" alt="Schermafbeelding 2022-06-08 om 13 44 30" src="https://user-images.githubusercontent.com/1572885/172608804-4f7ac588-f159-4be2-882e-3e2ceac32605.png">

Example: projects
In the future, more information could be useful here that you d
<img width="1178" alt="Schermafbeelding 2022-06-02 om 15 42 54" src="https://user-images.githubusercontent.com/1572885/172612853-51e61429-7a9e-480a-ba39-ee59630c41ae.png">
on't need to see on first sight.

Example of collapsable information in the old interface
<img width="779" alt="Schermafbeelding 2022-06-08 om 16 13 14" src="https://user-images.githubusercontent.com/1572885/172638887-e6aa35b7-8b54-42ca-94d7-074856400ce8.png">

Example of way too many authors:
<img width="779" alt="Schermafbeelding 2022-06-08 om 16 17 59" src="https://user-images.githubusercontent.com/1572885/172639826-85c73020-31ae-4125-86f7-8bd7b768c50e.png">

**Comment by emilyvandewalle** [comment]
## Design proposal

The designs for this issue can be found [here](https://www.figma.com/file/YKfocx0xpkuuyQUa3qt70P/Biblio---GitHub-issues?node-id=3%3A1969)

Still giving the layout/visual hierarchy of the list item a bit more thought, but this is where I've landed so far:

**Overview with all items collapsed:**

![image](https://user-images.githubusercontent.com/36261498/176624833-55d2dc49-d705-4c84-b0aa-b265a0c634db.png)

**Overview with some items expanded:**

![image](https://user-images.githubusercontent.com/36261498/176626926-f673c52f-a57b-42d7-903e-24ca8b3500a7.png)

- Since the list of authors can be very long, I've placed them in a column grid to add some structure. 
- Since reviewers mostly want to check the UGent authors I was wondering if it could make sense to add a filter at the top to show
    -  All authors
    - UGent authors only
    - External authors only

![image](https://user-images.githubusercontent.com/36261498/176627398-bf6c59ff-a063-4269-9f5e-a82335d42d46.png)


## Buttons at the bottom

While taking a look at this issue I also experimented with placing all controls at the bottom of a list item:

![image](https://user-images.githubusercontent.com/36261498/176627864-d4982816-4cc1-4792-b220-ad5026e7e625.png)

My concern is how to consistently apply this pattern with buttons at the bottom of list items throughout the entire application (publication detail headers, etc.)

## Alternatives

An alternative to show more information from the overview page could be a popover with more details, similar to what Github does when hovering over an issue  (but then maybe by clicking on a trigger like the show more button above). 

The benefit here could be that the list items don't change height/the content doesn't jump when expanding the more info panel, but then it wouldn't be possible to view more details of multiple items at the same time

<img width="420" alt="image" src="https://user-images.githubusercontent.com/36261498/176628422-4edb97c5-08fe-48e1-91f9-219ffc36b4e8.png">

## Questions

- What is your overall feedback on the proposal above?
- What do you think about the filter to view UGent authors only?
- What do you think about the layout with the buttons at the bottom of a list item?
- Would you like me to explore the alternative solution? Would it be helpful to view more details of multiple items at the same time?

**Comment by mietcls** [comment]
Thank you for these thorough explorations. I think the “show more” at the bottom, with the other buttons consistent at the top will be clear and feasible.

**The grid of 3**
Seems great, I want to test it with actual data (long names), but it seems like a good solution.

**Show UGent only**
I’ll suggest this one, but they usually want to check if _all of them_ are in there too to have a correct bibliography. But I’ll need to check if my assumption is correct!

**Buttons at the bottom**
To me putting all the actions at the bottom is a bit _busier_ overall when you look at the overall design. Good experiment, but the list items seem to be less of a unit (perhaps it’s the line above the actions?). I haven’t looked at it for a while so I think it’s not just the “being used to the previous design”.

**The popover**
I like the idea of information not hopping around. The popover would be good if you click it and it does not disappear if you navigate away or click on it. The librarians often copy information. We can look into this in the next round, interesting!

**Comment by emilyvandewalle** [comment]
Thanks a lot for the feedback!

I've added a generic example of a list item with expandable content in the [documentation](https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-list-group.html#component-09-list-group-items-more-details) and have also applied it to the [publication overview](https://biblio-ugent-prototype-emily-v2.vercel.app/biblio/reviewer/publications/overview--list.html) screens 

**Toggle to show more details:**
``` html
<button class="btn btn-link btn-link-p-0 btn-sm mt-4" type="button" data-toggle="collapse" data-target="#moreDetails-0" aria-expanded="false" aria-controls="null">
    <div class="btn-text">More details</div>
    <i class="if if-chevron-down"></i>
</button>
```

**Card with more details in a [definition list](https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/c-dl.html)**
``` html
<div class="collapse u-no-transition mt-5" id="moreDetails-0">
      <div class="card">
          <div class="card-body bg-lightest">
              <dl class="c-dl row c-body-small align-items-start px-3">
                  <dt class="col-md-2 c-dl-term">Label</dt>
                  <dd class="col-md-10 c-dl-desc">Value</dd>
              </dl>
          </div>
      </div>
  </div>
```
