### ISSUE TITLE
Eliminate tabs for now, and put all information on one page.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#426]
# UX Bug

There have been cases of secretariats that normally fill out records impeccably now forgetting to add authors and the full text. The chance that datasets will be forgotten is derived from these cases as well.

# Temporary enhancement

Eliminate the tabs:
- Full text
- Authors & Editors
- Datasets

And put the blocks in the first tab as one big form.

![Image](https://user-images.githubusercontent.com/1572885/187679290-578c7694-39da-481b-b61f-069c52b4aabf.png)
![Image](https://user-images.githubusercontent.com/1572885/187679291-25bc0404-f7d6-446b-bab5-5fc032f199e9.png)

# Not in scope

We will not be able to guide people from one tab to another right now. We will solve this at a later stage.

**Comment by mietcls** [comment]
Context: Matthias mentioned that the tabs have just been refactored. Keep in mind; if we have to put them back – there will be triple work...

**Comment by mietcls** [comment]
We will first test with the new validation, and revisit after.

**Comment by nicolasfranck** [comment]
Forgetting to fill in things is not just due to the existence of the tabs.
If you have to long list of files/authors, then you also not see certain things,
like a missing ugent author.

Why not a number next to author and file tab that indicates absence of authors/files?
Maybe in orange when there are none?

Description | Full text (0) | Authors (1)

Adding some sort of summary at the start for some stuff can be helpful for this purpose.
I do this also in my dashboards ("tiff files (2), jpeg files (1)")

**Comment by mietcls** [comment]
@nicolasfranck definitely a nice improvement once we have the plumbing! For now we don't have a good structural way to guide people to those tabs. If we have proper guidance, those indications in the tabs would be very useful.

The summary page for now unfortunately is not meaningful because the rules are not defined, which results into lying to the researchers (e.g. "everything is fine" or "everything is broken" with little nuance). Once those rules are defined, we can _bring it back from the deprecated_.

**Comment by mietcls** [comment]
Probably fixed by #331

**Comment by mietcls** [comment]
Not fixed. We still get reports. Need to get a new design for it. Analysis is being made.

**Comment by mietcls** [comment]
Redesign in progress.
