### ISSUE TITLE
Cryptic error shows when librecat backend throws HTTP 500

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backend#45]
**Describe the bug**

When you navigate to the detail page of a publication and Librecat throws back a HTTP 500 error, you're greeted with this cryptic message:

```
invalid character 'A' looking for beginning of value
```

We need to throw a proper human readable error to the end user when this happen.

**Comment by netsensei** [comment]
The global handler of Librecat should return JSON objects instead of HTML.

**Comment by nicolasfranck** [comment]
already done for a 404 within prefix `/librecat/rest-api`.
Do globally when something dies within Dancer and requested
content-type is json?

**Comment by nicolasfranck** [comment]
I've looked into the Dancer error hooks (what happens if something
"dies"), and it seems to be hardwired to do the following:

* render the exception with attributes `error` and `exception` and serialize it with the globally configured serializer
* if setting `show_errors: 0`, then render a html page with a vague message `an internal error occurred`

As this all happens globally, I see no way to interfere, operating from the hooks alone.

Anyway, if all things fail at the librecat side, it should be handled on the side of the biblio-backend, right?
Faulty response or "connection failed", it is all the same, not?

**Comment by nicolasfranck** [comment]
A interesting way to handle this in biblio-backend that I've seen is: generate an id, and put that id together with the exception somewhere in the log. And report that id to the end user ("something happened. Refer to id <id>"). That way you do not have to expose the error, but end users can report the exact time and place where it happened..

**Comment by nics** [comment]
work to be done: handle json response parse failures gracefully on the go side
