### ISSUE TITLE
bibtex often do not work

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backend#462]
**Example 1**: 
[scopus.bib.example_1.txt](https://github.com/ugent-library/biblio-backend/files/9240798/scopus.bib.example_1.txt)

File contains 22 entries

* golang code imports `0` entries

Due to comments at the start of the file:

```
Scopus
EXPORT DATE: 2 August 2022

@ARTICLE{Karamanou2022168,
```

Is that even allowed?

* `Catmandu::Importer::BibTeX` imports one records and then fails with

```
Oops! Malformed entry (key contains illegal characters) at {Ram?rez-Giraldo2022, ignoring
```

**Example 2**:
[scopus.bib.example_2.txt](https://github.com/ugent-library/biblio-backend/files/9240842/scopus.bib.example_2.txt)

Same file as previous, but now the leading comments are removed

* golang code imports one entry

* `Catmandu::Importer::BibTeX` imports one records and then fails with

```
Oops! Malformed entry (key contains illegal characters) at {Ram?rez-Giraldo2022, ignoring
```

Seems like accents in identifiers are not allowed? Although according to the perl implementation.

**Comment by nicolasfranck** [comment]
https://biblatex-linter.herokuapp.com/ does not complain about any of these problems

**Comment by mietcls** [comment]
@nicolasfranck does this bug still exist in the new Eliot version?

**Comment by nicolasfranck** [comment]
@mietcls  yes

**Comment by netsensei** [comment]
We use a 3rd party library to parse Bibtex: https://github.com/nickng/bibtex. It comes with its own command line tool, so I used that to test the bibtex files directly instead of importing in Biblio Backend.

I see the same issues:

The tool doesn't parse the first file due to the comments at the start of the file. It doesn't thrown error or any output either. So, there's no telling what went wrong.

Removing the comments and trying again: only the first entry in an export from Scopus search results is parsed. Not all of them. I don't get any errors.  I suspect the parser fails silently on the second record with the non-ascii characters too.

There are 3 options here:

* Looking at the code of the parser, debugging is non-trivial. Opening an issue with them is an option, but there are no assurances when or even if this is going to be fixed.
* Alternatively, we could try looking for a different Bibtex parser written in Go.
* Absolute last resort is writing our own implementation.

Another option is having users manually correct their data before importing. But that would require validation and proper error handling implemented by any parser we would use in order to notify users of what went wrong. Quick fixes - e.g. writing glue code to chop off Scopus comments  before parsing - would only be a band aid solution: depending on the origin, variations on Bibtex format may be imported and it's no use trying to take into account / rectifying the quirks of each potential variation.

**Comment by nics** [comment]
2 points:

- a good bibtex importer is important for people migrating their bibliography to biblio, some systems only have a bibtex export
- there is no good Go bibtex parser, we'll probably end up writing our own (mostly a translation job, shouldn't take too long)

**Comment by nics** [comment]
since 586f39c9774c1bce554ff8ff746347c99d489596 the bibtex importer only fails on the illegal characters (same behaviour as the Perl version)

**Comment by nics** [comment]
> https://biblatex-linter.herokuapp.com/ does not complain about any of these problems

this linter doesn't work correctly (see it's github repo)

**Comment by nicolasfranck** [comment]
`Author-Email` from Scopus contains an unescaped `@`, which is of course wrong. Should be `\&`.
We do not use these fields, but it gives an `Unexpected @ at ..`
