### ISSUE TITLE
Remove dropdown publications and detail page page on top right if no buttons are available

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#550]
# Story

There's a dropdown button without any actions connected to it on the top right of the publications overview page.

Question: what was supposed to be in it?
Related: add "Export to excel" functionality. If there are more "extra" actions, we can use the extra "actions" button again, but as long as there are no extra secondary actions we probably do not need it.
https://github.com/ugent-library/biblio-backend/issues/555: describes the export functionality that can be in here if needed, but not for now.

# Context

Current implementation:
![Image](https://user-images.githubusercontent.com/1572885/188461578-aaaf5811-07cd-4f59-915d-fa609fc1fb88.png)

**Comment by netsensei** [comment]
On closer inspection, this contextual menu currently contains 1 item: "Send my publications to ORCID".  It's a bulk action which will send all the publications having the user as an author, to ORCID.

If you don't have an ORCID ID and ORCID Token associated with your user account, this action will be omitted from the menu. Since it's the only option, it will leave just the button and an empty box.

@mietcls Suggestion: convert the "Send my publications to ORCID" into a dedicated button next to "Export to Excel" and "Add publication" for the time being?

**Comment by mietcls** [comment]
@netsensei thanks for catching that one!
With the related issue in mind I think it would probably most consistent / easiest to turn it into dedicated buttons, as the menu is not that cluttered yet. I'll move it to "in review" again until we have a better view of what the cards will look like with all the information inside (related: "details" elapse/collapse)

**Comment by mietcls** [comment]
@netsensei is the functionality to "Send my publications to ORCID" also visible in the librarian mode, or is it removed then?

**Comment by netsensei** [comment]
@mietcls That feature has existed since before the split researcher / librarian mode. I think it's only considered from the perspective of the researcher. @nics Does it make sense to have a "send these publications to ORCID" from the point of view of the librarian?

**Comment by mietcls** [comment]
@netsensei @nics I have thought of a second solution that will cover all cases in this issue: https://github.com/ugent-library/biblio-backend/issues/623 (we can close this one as a "not planned" if we go for this solution).

**Comment by netsensei** [comment]
I like #623. Though I think the discussion of functionality in the dropdown in this issue is mainly a question of visualization. Do we stuff a list of actionable items below a dropdown? Or do we present them as a plain visible list of buttons?  Since #623 is definitely a call to action that wants to be visible, keeping the dropdown makes even less sense.

To my mind, the dropdown menu would make sense if the UI becomes too cluttered with a string of buttons and actions.

**Comment by mietcls** [comment]
@netsensei when looking at these issues:
https://github.com/ugent-library/biblio-backend/issues/565
https://github.com/ugent-library/biblio-backend/issues/565

I think it might get too cluttered at some point and draw away attention from the main actions (especially for "veelinvoerders" and librarians). I don't mind keeping the dropdown as in the future we might add other functionalities (such as delete on detail pages).

**Comment by mietcls** [comment]
Thank you for flying with us today.
