### ISSUE TITLE
If a record is withdrawn, I can see it in the publications and datasets overview.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#580]
# Story

If a record is withdrawn, I can see it in the publications and datasets overview.

Read the context here: https://github.com/ugent-library/biblio-backend/issues/578

## Success criteria
- [ ] The moment a record is withdrawn, I can see it in the overview for datasets and publications with a badge
  - [ ] The status is set to "Biblio Withdrawn"
  - [ ] [TO BE DISCUSSED] The visibility is set to "Private"

# Implementation

## Adapted design for current Biblio
<img width="1038" alt="188880756-8393f4e3-fd56-41a0-99e2-a8abe90976e2" src="https://user-images.githubusercontent.com/1572885/190352106-f2b8414d-0ba4-413d-a6e2-c001119fbf5e.png">

## Reference to original design
<img width="1041" alt="Schermafbeelding 2022-09-07 om 14 40 57" src="https://user-images.githubusercontent.com/1572885/188880660-7fb6fb90-78f6-4495-9ce9-92071f6c4fc8.png">

## Component
Danger badge: https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-badges.html#component-01-b-badge-text

## Example code for current implementation
```
<div class="list-group-item-meta-left">
  <div class="list-group-item-meta-item">
    <span class="badge badge-pill badge-danger">
      <span class="badge-text">Biblio Withdrawn</span>
    </span>
  </div>
</div>
```

**Comment by netsensei** [comment]
There are currently 4 values defined:

* Private
* Public
* Deleted
* Withdrawn

Private equates to the "draft" state of the record: before the record is first posted / made public on Biblio.  Whereas the withdrawn state refers to a record that has already been published before.

As a result, marking "withdrawn" records with the "private" status would make it impossible to differentiate between the two states. We do require a separate "withdrawn" status in order to be able to filter and visibly indicate records which have been withdrawn.

**Comment by mietcls** [comment]
@netsensei thank you for zooming in, I missed something in the code snippet. The status private should indeed not be in there.

To make sure – I think we're on the same page; withdrawn is not visible to the main public, correct?

I'll rectify it.
