### ISSUE TITLE
more obvious WoS import and/ WoS ID-based import

### ISSUE THREAD

**Issue by anniekt** [ugent-library/biblio-backend#64]
voorbeeld: 
https://www.webofscience.com/wos/woscc/full-record/WOS:000576944100018
er staat geen doi in WOS, dus moet dit manueel?

Soms bestaat er wel een doi, maar is die niet opgenomen in WOS.

*********************************************************************

**Describe the improvement**
A clear and concise description of what the improvement is.

**To Reproduce**
If something does not work as expected, which steps did you take?

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by sdebodt** [comment]
Anniek informed me that the WOS ID is currently the most important ID. It needs to be added to the "add single publication" workflow as well. Disadvantage of using the DOI is that the WOS ID needs to be manually added by the reviewer as it is not always automatically entered during DOI-based import.

**Comment by sdebodt** [comment]
Currently, a single publication can be added based on WOS file through the "add multiple publications" workflow. Adding WOS ID in the "add single publication" workflow will be implemented in a later stage, which will then increase efficiency in which a single publication can be added through a WOS ID.
Complication due to limitations on use of WOS API.

**Comment by sdebodt** [comment]
- consider to add import using WoS export on "add single publication" workflow.
- can the WoS API be used to retrieve metadata based on DOI and does this return more metadata than the CrossRef API?
