### ISSUE TITLE
Question; datasets double check bij import?

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#677]
# Question

Will the datasets get a double check at import as well?

**Comment by netsensei** [comment]
On import a dataset as well as publications gets a "double" check.

* If there's already an existing, identical dataset with the status "public", the user will get a warning modal.

The warning modal is only informative. This gives the user a lot of freedom. It's possible to import the same dataset as multiple, discrete records. e.g. you could have 2 records of the same dataset with the status "public".  Since we can't guess the intentions of researchers, it's okay to give them so much leeway. It's up to reviewers to assure that there are no big issues.
