### ISSUE TITLE
How to report errors during batch imports (wos, ris)?

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backend#72]
**Story**

When you try to add multiple publications by uploading a RIS file,
one or more publications may contain attributes that are "valid"
according to the internal publication validator of LibreCat.
How to report this to the end user? 

"999 added, one failed, try to find it.."

**Comment by netsensei** [comment]
Per the discussion on Slack: we've decided for an "all or nothing" approach.

If one publication contains an invalid attribute, the entire batch needs to be rolled back in Librecat. Per @nicolasfranck: This has been implemented in Librecat. 

The Librecat REST API returns an error which arrives in the Go controller, but isn't displayed lack because we an affordance to show flash messages at the moment.
